// examples/solid/app.tsx
import { createSignal, onCleanup } from "solid-js";
import { Config } from "@raubjo/architect-core";
import { useService } from "@raubjo/architect-core/solid";
import CounterService from "./counter/service";
import HeartbeatService from "./heartbeat/service";

export default function App() {
  const counter = useService(CounterService);
  const [value, setValue] = createSignal(counter.current());
  const heartbeat = useService(HeartbeatService);
  const [ticks, setTicks] = createSignal(heartbeat.ticks());
  const [status, setStatus] = createSignal(heartbeat.status());

  const unsubscribe = heartbeat.subscribe((state) => {
    setTicks(state.ticks);
    setStatus(state.status);
  });

  onCleanup(() => {
    unsubscribe();
  });

  return (
    <>
      <h1>{String(Config.get("app.name"))}</h1>
      <h1>Heartbeat service: {ticks()} ({status()})</h1>
      <button
        onClick={() => {
          counter.increment();
          setValue(counter.current());
        }}
      >
        Counter Service: {value()}
      </button>
      <button onClick={() => heartbeat.toggle()}>Toggle Heartbeat</button>
    </>
  );
}

// examples/react/app.tsx
import { ReactNode, useState } from "react";

import { Config  } from "@raubjo/architect-core";
import { useService } from "@raubjo/architect-core/react";

import CounterService from "./counter/service";
import Heartbeat from "./heartbeat/service";

export default function App() {
  const counter = useService<CounterService>(CounterService);
  const [value, setValue] = useState(counter.current());

  const heartbeat = useService<Heartbeat>(Heartbeat);

  function increment() {
    counter.increment();
    setValue(counter.current());
  }

  return (
    <>
    <h1>{Config.get<string>('app.name') as ReactNode}</h1>
    <h1>Heartbeat service: {heartbeat.ticks()}</h1>
    <button onClick={increment}>Counter Service: {value}</button>
    </>
  );
}
